### ISSUE TITLE
matplotlib version

### ISSUE THREAD

**Issue by mahdikooshkbaghi** [jbkinney/mavenn#10]
Hi,
Installing through `pip` did not update the required `matplotlib`. 
I needed to update the `matplotlib` manually.
Seems `mavenn` needs `matplotllib>3.3.2`.

**Comment by mahdikooshkbaghi** [comment]
My `mavenn` version is `0.22`.

**Comment by atareen** [comment]
Thanks for checking, I'll add that to the list of todos.

**Comment by atareen** [comment]
version 3.2.0 was working well for me, so I put matplotlib>=3.2.0 in this release. Let me know if causes any issues in the future.
