### ISSUE TITLE
`tutorial_0_built-in_examples` training set

### ISSUE THREAD

**Issue by mahdikooshkbaghi** [jbkinney/mavenn#11]
Hi,
with `mavenn 0.22`, in the following cell we have `KeyError: 'training_set'`.

```python
# indices of training examples
i_training = mpsa_df['training_set']

# get test examples.
mpsa_test_df = mpsa_df[~i_training]

print('Test mpsa values:')
mpsa_test_df.head()
```

The `mpsa_df = mavenn.load_example_dataset(name='mpsa')` returns the pandas dataframe with the following columns:

|set | tot_ct | ex_ct | y | x|
|--- | --- | --- | --- | ---|
|training | 28 | 2 | -3.273018 | GGAGUGAUG|
|training | 315 | 7 | -5.303781 | AGUGUGCAA|
|test | 193 | 15 | -3.599913 | UUCGCGCCA|
|validation | 27 | 0 | -4.807355 | UAAGCUUUU|
|training | 130 | 2 | -5.448461 | AUGGUCGGG|

The solution was change the line to the following:
```python
mpsa_test_df = mpsa_df[mpsa_df['set']=='test']
```

**Comment by atareen** [comment]
Hi Mahdi, this is set to be updated in the next release. Thanks for checking.

**Comment by atareen** [comment]
Hi Mahdi, I've updated this tutorial as part of the new release, can you try again?

**Comment by mahdikooshkbaghi** [comment]
Hi Ammar,
I can confirm the Notebook example run from the beginning to the end without any issue with `mavenn 0.23`.
Thanks.
