### ISSUE TITLE
Does not install with Python 3.8

### ISSUE THREAD

**Issue by laserson** [jbkinney/mavenn#6]
I'm trying to install using a fresh conda env with Python 3.8. Apparently cvxopts 1.1.9 is not compatible with Python 3.8? (At least according to conda)

(I also got an issue about numpy being required btw.)

Is it possible to simplify the installation process somehow? Are all the libraries really required to be pinned to those exact versions?

Or perhaps you could set up some CI to test builds in fresh environments on different python versions?

**Comment by laserson** [comment]
I think numpy is a requirement for pymc, but apparently doesn't get pulled in

**Comment by laserson** [comment]
Note that MarkupSafe is also broken. You pin to 1.0, which uses `from setuptools import Feature`, but the latter has been removed in the latest version of setuptools. Conda installing MarkupSafe seems to work.

**Comment by atareen** [comment]
Hi Uri, 

We're currently in the process of revamping this entire project. We should be able to do a new release in the near future and I'll work on ease of installation and check dependencies etc. then. 

In the current state of the project, you can try the following: 

- Follow the instructions here https://mpathic.readthedocs.io/en/latest/ using virtualenv. 
- Try the install on google colab

What are you looking to use MPAthic for? Are you looking to infer sequence-function models or something else?
