### ISSUE TITLE
Enhancement to tutorial_0

### ISSUE THREAD

**Issue by jbkinney** [jbkinney/mavenn#7]
Illustrate usage of load_example_dataset() and load_example_model() in tutorials/tutorial_0_built-in_examples.ipynb

**Comment by atareen** [comment]
I have updated tutorial 0 illustrating the use of the load_example method:
https://github.com/jbkinney/mavenn/blob/master/mavenn/examples/tutorials/tutorial_0_built-in_examples.ipynb
