### ISSUE TITLE
Enhance interface to examples

### ISSUE THREAD

**Issue by jbkinney** [jbkinney/mavenn#8]
Unify load_example_dataset() and load_example_model() into one function, load_example(), from which the user can request the training data, test data, or inferred model. Can be done with `which="model"`, `which="training_data"`, `which="test_data"`

**Comment by atareen** [comment]
I've added the method load_example: https://github.com/jbkinney/mavenn/commit/44af387625362d2461cad61778ecbf43a88e20af

I will close this issue after I writing tests for it.

**Comment by atareen** [comment]
I've added tests for the load_example; currently all tests are passing:
https://github.com/jbkinney/mavenn/commit/190430c54855c0175e3afcf26e308e41e76636f0

I am closing this issue now, but will use this updated method to expand on tutorial_0.
